Repository MryashAditya007/Hacktoberfest2023, pull requests merged in 2022-10, with the labels that each got.

#10 Added Calculator
  Python/calculator.py
  README.md
Labels: hacktoberfest2022, hacktoberfest-accepted

#22 Added hackerrank solution to various problems in JAVA programming lan…
  Hackerrank/Java/Array_left_rotation.java
  Hackerrank/Java/Arrays_ds.java
  Hackerrank/Java/Crush.java
  Hackerrank/Java/Java_anagrams.java
  Hackerrank/Java/Java_currency_formatter.java
  Hackerrank/Java/Java_loops.java
  Hackerrank/Java/Java_loops_i.java
  Hackerrank/Java/Java_string_reverse.java
  Hackerrank/Java/Sparse_arrays.java
  README.md
Labels: documentation, hacktoberfest2022, hacktoberfest-accepted

#23 matrix addition in cpp
  Codechef_C++/matrixadd.cpp
  README.md
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#24 DataScience_MLproject_Property_Price_Prediction_model.ipynb
  DataScience_MLproject_Property_Price_Prediction_model.ipynb
Labels: hacktoberfest2022, hacktoberfest-accepted

#27 Create Optimal use of Nuclear Power plant
  Codechef_C++/Optimal use of Nuclear Power plant
  README.md
Labels: hacktoberfest2022, hacktoberfest-accepted

#28 Added Hackerrank solution to Java and C languages
  Hackerrank/C/C_Variadic_funtions_in_C.c
  Hackerrank/C/C_post_transition.c
  Hackerrank/C/C_querying_the_document.c
  Hackerrank/C/C_small_triangle_large_triangles.c
  Hackerrank/C/C_sorting_array_of_Strings.c
  Hackerrank/C/C_structuring_the_document.c
  Hackerrank/Java/Java_date_and_time.java
  Hackerrank/Java/Java_end_of_file.java
  README.md
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#29 C_Digit_Frequency
  Hackerrank/C/C_Digit_frequency.c
Labels: hacktoberfest2022, hacktoberfest-accepted

#34 Program to display calendar of month and year
  Python/Display_Calendar.py
  README.md
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#37 Create Orandcon.cpp
  Codechef_C++/Orandcon.cpp
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#38 Added Python Script for converting JSON to CSV
  Python/Convert_JSON_to_CSV/converter.py
  Python/Convert_JSON_to_CSV/input.json
  Python/Convert_JSON_to_CSV/output.csv
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#42 Hate & Offensive Content Detection Code & Data Added
  Data Science Projects/Hate & Offensive Content Detection/Hate Content Detection.csv
  Data Science Projects/Hate & Offensive Content Detection/Hate_And_Offensive_Content_Detection.ipynb
  Data Science Projects/Hate & Offensive Content Detection/README.md
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#41 Added Tictactoe game
  Python/tictactoe.py
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#40 Password generateor porgram
  Python/Password_generator.py
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#45 Create MedianMarks
  MedianMarks
Labels: hacktoberfest2022

#46 Create File Explorer in Python using Tkinter
  Python/File_explorer.py
  README.md
Labels: good first issue, hacktoberfest-accepted

#48 Hangman
  Python Games/Hangman.py
  README.md
Labels: hacktoberfest2022, hacktoberfest-accepted

#49 Contributed two codes in java language from codechef
  Codechef/JAVA/MINCARS.java
  Codechef/JAVA/WATERCOOLER1.java
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#50 Create Selection_Sort.py
  Python/Selection_Sort.py
Labels: good first issue, hacktoberfest2022, hacktoberfest-accepted

#53 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest

#58 Create Shell Sort
  Codechef_C++/ShellSort.cpp
Labels: good first issue, hacktoberfest2022, hacktoberfest

#57 Added solution of one of the codechef problem
  Codechef_C++/magic_element.cpp
Labels: good first issue, hacktoberfest

#63 Modified the headings so that it stand out from the content : )
  README.md
Labels: good first issue, hacktoberfest-accepted

#64 Java Subarrays | Hackerrank Medium problem
  Hackerrank/Java/Java_Subarray.java
Labels: hacktoberfest-accepted

#65 Added codechef solution.
  Codechef_C++/atm_machine.cpp
Labels: hacktoberfest-accepted

#68 Smallest_Even_Multiple
  Codechef_C++/Smallest_Even_Multiple
Labels: hacktoberfest-accepted

#67 Create all-ancestors-of-a-node-in-a-directed-acyclic-graph.py added
  Python/all-ancestors-of-a-node-in-a-directed-acyclic-graph.py
Labels: hacktoberfest-accepted
