Repository MryashAditya007/Hacktoberfest2023, pull requests merged in 2023-10, with the labels that each got.

#77 Added DP codes to enhance the repo programs
  Problems/Dynamic Programming/1_Climbing_Stairs.cpp
  Problems/Dynamic Programming/1_Fibonacci_Series.cpp
  Problems/Dynamic Programming/2_Min_Cost_Climbing_Stairs.cpp
Labels: hacktoberfest-accepted

#76 Create Program to Concatenate Two Strings.cpp
  Codechef_C++/Program to Concatenate Two Strings.cpp
Labels: Hactoberfest, hacktoberfest-accepted

#94 letter-combinations-of-a-phone-number
  LeetCode/letter-combinations-of-a-phone-number.java
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#91 added my name in readme
  README.md
Labels: hacktoberfest-accepted

#97 readmefile update
  README.md
Labels: hacktoberfest-accepted

#98 longest common prefix
  LeetCode/longest-common-prefix.cpp
  README.md
Labels: hacktoberfest-accepted, good-first-issue

#87 Written program to concatenate string using C++
  ConcatString.cpp
  README.md
Labels: hacktoberfest-accepted, hacktoberfest, good-first-issue

#99 longest consecutive sequence
  LeetCode/longest-consecutive-sequence.cpp
Labels: hacktoberfest-accepted, good-first-issue

#100 Rename ConcatString.cpp to C++/ConcatString.cpp
  C++/ConcatString.cpp
Labels: hacktoberfest-accepted, good-first-issue

#101 Create LinkedListCycle.java
  LeetCode/LinkedListCycle.java
Labels: hacktoberfest-accepted

#109 Update README.md
  README.md
Labels: hacktoberfest-accepted

#108 #106 solved
  LeetCode/3sum.cpp
Labels: hacktoberfest-accepted

#134 Added Leetcode problems
  LeetCode/C++/3sum.cpp
  LeetCode/C++/longest-common-prefix.cpp
  LeetCode/C++/longest-consecutive-sequence.cpp
  LeetCode/JAVA/LinkedListCycle.java
  LeetCode/JAVA/letter-combinations-of-a-phone-number.java
  Leetcode/JAVA/Divide_Two_Numbers.java
  Leetcode/JAVA/Rotate_Image.java
  README.md
Labels: Hactoberfest, hacktoberfest-accepted

#145 Create bubble_sort.cpp
  C++/bubble_sort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#144 Create Swap_Nodes_in_Pairs.java
  LeetCode/JAVA/Swap_Nodes_in_Pairs.java
Labels: hacktoberfest-accepted, hacktoberfest

#143 Face Emotion Recognition using inceptionNet
  Data Science Projects/Face Emotion Recognition /Readme.md
  Data Science Projects/Face Emotion Recognition/InceptionNet.ipynb
  Data Science Projects/Face Emotion Recognition/Preprocessing.ipynb
  Data Science Projects/Face Emotion Recognition/haarcascade_frontalface_default.xml
  Data Science Projects/Face Emotion Recognition/inception-net predictions.ipynb
Labels: hacktoberfest-accepted

#141 Create n-queen.cpp
  C++/n-queen.cpp
Labels: hacktoberfest-accepted

#125 Create Insert_nose_at_tail.cpp
  C++/insert_node_at_tail.cpp
  README.md
Labels: hacktoberfest-accepted, hacktoberfest

#149 Added Rock Paper Scissors Game.
  Python Games/Rock_Paper_Scissor.py
Labels: documentation

#156 Added Paining the walls problem in java leetcode solutions
  LeetCode/JAVA/Paintingthewalls.java
  README.md
Labels: hacktoberfest-accepted

#152 Some useful AI Algorithms Python
  Python/8puzzle.py
  Python/alphabeta.py
  Python/dfs-id.py
  Python/dfs.py
Labels: hacktoberfest-accepted

#151 Create SelectionSort.cpp
  C++/SelectionSort.cpp
Labels: hacktoberfest-accepted, hacktoberfest

#155 Two_sum problem from leetcode
  LeetCode/JAVA/Two_sum
Labels: hacktoberfest-accepted

#158 Create downlvid.py
  downlvid.py
Labels: hacktoberfest-accepted

#159 bestTime_to_buyAndsell_Stock
  LeetCode/JAVA/bestTime_to_buyAndsell_Stock
Labels: hacktoberfest-accepted

#160 Added Hackerrank SQL solutions solving #78
  Japanese Cities Attributes.sql
  Japanese Cities Name.sql
  Revising the Select Query I.sql
  Revising the Select Query II.sql
  Select All.sql
  Select by ID.sql
  Weather Observation Station 1.sql
  Weather Observation Station 10.sql
  Weather Observation Station 11.sql
  Weather Observation Station 12.sql
  Weather Observation Station 3.sql
  Weather Observation Station 4.sql
  Weather Observation Station 5.sql
  Weather Observation Station 6.sql
  Weather Observation Station 7.sql
  Weather Observation Station 8.sql
  Weather Observation Station 9.sql
Labels: hacktoberfest-accepted

#147 Create radix_sort.cpp
  C++/radix_sort.cpp
Labels: hacktoberfest-accepted

#167 Create sub_array.cpp
  Codechef_C++/sub_array.cpp
Labels: hacktoberfest-accepted

#81 Added Ball distribution problrm and its solution
  Codechef_C++/Ball_Distribution.cpp
Labels: hacktoberfest-accepted

#115 Create Remove_duplicates_from_sorted_array.cpp
  LeetCode/Remove_duplicates_from_sorted_array.cpp
Labels: Hactoberfest, hacktoberfest-accepted

#166 Create quickSort.cpp
  C++/quickSort.cpp
Labels: hacktoberfest-accepted

#163 Create Ternary Tree.cpp
  C++/Ternary Tree.cpp
Labels: hacktoberfest-accepted

#140 DSA Sorting CPP
  Sorting CPP/01_Bubble_Sort.cpp
  Sorting CPP/02_Insertion_Sort.cpp
  Sorting CPP/03_Selection_Sort.cpp
  Sorting CPP/04_Quick_Sort.cpp
  Sorting CPP/05_Merge_Sort.cpp
Labels: hacktoberfest-accepted

#136 Create linear_search.cpp
  C++/linear_search.cpp
Labels: hacktoberfest-accepted

#131 Create weather-observation-station-5.sql
  HackerRank/weather-observation-station-5.sql
Labels: hacktoberfest-accepted

#129 Added Java If-Else from HackeRank and Solved it and Update README.md
  Hackerrank/Java/Java_If_Else.java
  README.md
Labels: hacktoberfest-accepted

#184 2 sum problem in java
  LeetCode/.DS_Store
  LeetCode/C++/.DS_Store
  LeetCode/JAVA/2sum.java
Labels: hacktoberfest-accepted

#187 Rock_Paper_Scissors #123
  Python Games/rock_paper_scissors1.py
Labels: hacktoberfest-accepted

#117 Leetcode
  LeetCode/Longest Consecutive Sequence.cpp
  LeetCode/Maximum Subarray.cpp
  LeetCode/Text Justification.cpp
Labels: hacktoberfest-accepted

#121 Added Face Attendace System in Python
  Python/Face-Attendance-System/AddDataToDatabase.py
  Python/Face-Attendance-System/EncodeGenerator.py
  Python/Face-Attendance-System/Readme.md
  Python/Face-Attendance-System/Resources/Modes/1.png
  Python/Face-Attendance-System/Resources/Modes/2.png
  Python/Face-Attendance-System/Resources/Modes/3.png
  Python/Face-Attendance-System/Resources/Modes/4.png
  Python/Face-Attendance-System/Resources/background.png
  Python/Face-Attendance-System/dlib package install/dlib-19.22.99-cp310-cp310-win_amd64.whl
  Python/Face-Attendance-System/dlib package install/dlib-19.22.99-cp37-cp37m-win_amd64.whl
  Python/Face-Attendance-System/dlib package install/dlib-19.22.99-cp38-cp38-win_amd64.whl
  Python/Face-Attendance-System/dlib package install/dlib-19.22.99-cp39-cp39-win_amd64.whl
  Python/Face-Attendance-System/dlib package install/dlib-19.24.1-cp311-cp311-win_amd64.whl
  Python/Face-Attendance-System/main.py
Labels: hacktoberfest-accepted

#119 Create rock-paper-scissors.py
  Python Games/rock-paper-scissors.py
Labels: hacktoberfest-accepted

#128 Add chefandstocks.cpp
  Codechef_C++/chefandstocks.cpp
Labels: hacktoberfest-accepted

#179 Ayushharode patch 16
  C++/Jump Game II.cpp
  C++/Multiply Strings.cpp
  C++/Search in Rotated Sorted Array.cpp
  LeetCode/C++/Count and Say.cpp
  Substring with Concatenation of All Words.java
  Zigzag Conversion.java
  face_mask_detection.py
Labels: hacktoberfest-accepted

#171 Create QuickSort.cpp
  C++/QuickSort.cpp
Labels: hacktoberfest-accepted

#174 hacktoberfest
  LeetCode/C++/reverse-integer
  Python Games/tic_tac_toe.py
Labels: hacktoberfest-accepted

#176 Update README.md
  README.md
Labels: documentation, hacktoberfest-accepted

#180 Create sieveOfEratosthenes.cpp
  LeetCode/C++/sieveOfEratosthenes.cpp
Labels: hacktoberfest-accepted

#182 Create Merge_Two_Sorted_List.java
  LeetCode/JAVA/Merge_Two_Sorted_List.java
Labels: hacktoberfest-accepted

#189 Created merge_sort.cpp
  C++/merge_sort.cpp
Labels: hacktoberfest-accepted
